CREATE TABLE 'users' (
    'id' INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    'name' VARCHAR(75) NOT NULL,
    'password' VARCHAR(255) NOT NULL,
    'email' VARCHAR(100) NOT NULL,
    PRIMARY KEY ('id'),
    UNIQUE KEY 'email' ('email')
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI AUTO_INCREMENT=1;